services:
  - docker

before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - sudo mkdir .aws
  - echo "[default]" > .aws/config
  - echo "aws_access_key_id = \$AWS_ACCESS_KEY_ID" >> .aws/config
  - echo "aws_secret_access_key = \$AWS_SECRET_ACCESS_KEY" >> .aws/config
  - echo "region = us--east-2" >> .aws/config
  - aws ssm help
  - docker build -t curryari/tompencil .

script:
  - docker run -d --name testpencil curryari/tompencil 
  - docker exec testpencil curl localhost:80

after_success:
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push curryari/tompencil
#deploy:
#  provider: elasticbeanstalk
#  region: 'us-east-1'
#  app: 'multi-docker'
#  env: 'MultiDocker-env'
#  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#  bucket_path: 'docker-multi'
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
