services:
  - docker

before_install:
  - docker build -t curryari/tompencil .

script:
  - docker run -e CI=true --name testpencil curryari/tompencil
  - docker exec testpencil curl localhost:80

after_success:
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push curryari/tompencil
#deploy:
#  provider: elasticbeanstalk
#  region: 'us-east-1'
#  app: 'multi-docker'
#  env: 'MultiDocker-env'
#  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#  bucket_path: 'docker-multi'
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
